name: Build

on:
  push:

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.0

      - name: Build
        run: ./gradlew assemble

  test:
    name: Test
    needs: [ assemble ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.0

      - name: Test
        id: test
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v4.3.1
        if: ${{ failure() && steps.test.outcome == 'failure' }}
        with:
          name: test-report-${{ matrix.runner }}
          path: ./build/reports/tests/test/

      - name: Generate coverage report
        run: ./gradlew koverHtmlReport --exclude-task=test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4.3.1
        with:
          name: coverage-report-${{ matrix.runner }}
          path: ./build/reports/kover/html/

  lint:
    name: Lint
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.0

      - name: Run detekt analysis on main sources
        run: ./gradlew detektMain

      - name: Upload main detekt report for CodeQL
        uses: github/codeql-action/upload-sarif@v3.24.10
        if: ${{ ! cancelled() }}
        with:
          sarif_file: ./build/reports/detekt/main.sarif
          category: main

      - name: Run detekt analysis on test sources
        run: ./gradlew detektTest
        if: ${{ ! cancelled() }}

      - name: Upload test detekt report for CodeQL
        uses: github/codeql-action/upload-sarif@v3.24.10
        if: ${{ ! cancelled() }}
        with:
          sarif_file: ./build/reports/detekt/test.sarif
          category: test
